#configs/control.yaml

run_name: control

model_name: checkpoints/original

dataset: openhermes

output_dir: checkpoints/control

epochs: 1

learning_rate: 1e-5

weight_decay: 0.01

max_length: 2048

batch_size: 1

gradient_accumulation_steps: 16

save_steps: 200

bf16: true